### ISSUE TITLE
Coins to wallet

### ISSUE THREAD

**Issue by darrenhakimi** [limneos/MobileMiner#16] opened 2018-01-15 08:05 UTC
In MobileMiner, accepted states 8/8 (100%), but I do not see any coins added to my wallet on Electroneum. I checked my wallet address and it is correct. How long does it take for mined coins to be deposited into a wallet? Thank you.

**Comment by zarroukimouad** [comment] 2018-01-15 13:29
Me too , i m wating for it more than 12 hours

**Comment by darrenhakimi** [comment] 2018-01-17 07:30
My wallet balance is still 0 ETN. I tried mining a few times. I would appreciate some feedback. Thank you.

**Comment by dansinclair25** [comment] 2018-01-17 11:31
My guess (and it is only a guess), is that the coins you've mined will stay "unconfirmed" for while until the server has had a chance to confirm them and put them in your wallet. This seems to be the case when mining other cryptos. For other cryptos, this can take a few days.

**Comment by limneos** [comment] 2018-01-17 11:44
Guys, please, since these are general mining questions and not MobileMiner-related, post such kind of questions to related forums and not here. 

I will respond once just to explain, and then close this thread as it is not app-related , but general-mining-related.

1) Most important thing that most of you misunderstand:  
You mine to a pool, not directly to your wallet. 
This means that the pool that you have selected to mine to is responsible for displaying your current stats, pending balance and your total payouts, and eventually, transferring funds to your wallet.

2) Every pool has a minimum payout limit, which can vary from 5 ETN to 20 ETN or higher, depending on the pool. This means that even if you have gathered 18 ETNs so far but the pool's minimum payout is 20 ETN, they won't be transferred to your wallet until you reach 20 ETN.

3) To check your current balance, you open the pool's stats page url on your browser. 
Most pools use the same url for mining and for displaying stats, while others, use different urls for stats. 
For example, us-etn-pool.hashparty.io is the pool's mining address, whereas http://us-etn-stats.hashparty.io is the stats url for the pool. 
You open the stats url, paste your wallet address at the "Lookup" field at the bottom, and THERE you see your current balance, submissions and payouts. Once a minimum payout limit is reached and the pool makes the payout, /then/ you can see the amount in your wallet, in electroneum.com.

4) Finally , "Accepted 8/8 (100%)" means that you have successfully submitted 8 hashes out of 8 processed.
You usually need a few HUNDREDS of "accepted" hashes in order to get 1 ETN.

**Closed as completed by limneos** 2018-01-17 11:44 UTC
